### ISSUE TITLE
Multistalker icon logo

### ISSUE THREAD

**Issue by biko-73** [zKhadiri/MultiStalkerPro-releases#1]
please if you don't mind add multistalker icon logo designed by oktus
![icon](https://github.com/zKhadiri/MultiStalkerPro-releases/assets/57875905/85432e67-32c8-40a4-90cc-aa6cf436f8ce)
[icon.zip](https://github.com/zKhadiri/MultiStalkerPro-releases/files/14750170/icon.zip)

**Comment by zKhadiri** [comment]
Done, thanks.
